
spring:
  datasource:
    url: jdbc:postgresql://212.64.12.73:5432/demo
    username: admin
    password: 123456
  session:
    store-type: redis
  redis:
    host: 212.64.12.73
    port: 6379
    password: 123456